test: &default

  # Credentials for REST APIs
  client_id: AdOV0-MFfEGtR8DGA6sNJanl03ibgrF80sUqrVIX8KZikqaYDYCB_T99aWPTT8EF3qygx7zcQHcWqUaw
  client_secret: EEcNFr42ALljgtrQ64-f_pBm7QZYZ6wZM04bg0xfT3TCsN78WfK9rbphFlhnVCykWaC5giZbp6ydaLp9

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: darwin-seller@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
